@url = http://localhost:8080/api/meal
# @token =
# Authorization: Bearer {{token}}

### (Meal) FIND meal by id
GET {{url}}/1 HTTP/1.1

###
GET {{url}}/2 HTTP/1.1

###
GET {{url}}/3 HTTP/1.1

### (List<Meal>) FIND meals by x user
GET {{url}}/appUserId/1 HTTP/1.1

###
GET {{url}}/appUserId/2 HTTP/1.1

### ADD meal
POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "Hawaiian Pizza",
  "price": 7.75,
  "description": "It's got mozz my guy cmon",
  "lastUpdated": "2023-06-25T14:27:00",
  "appUserId": 2,
  "restaurantId": 1,
  "public": true
}

###
POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "Zepolle",
  "price": 2.00,
  "description": "Powdered donut basically",
  "lastUpdated": "2023-06-25T14:27:00",
  "appUserId": 2,
  "restaurantId": 2,
  "public": false
}

### UPDATE meal
PUT {{url}}/1
Content-Type: application/json
Accept: application/json

{
  "mealId": 1,
  "title": "Updated Title",
  "price": 7.75,
  "description": "Sweet potato bubble milk tea with creme.",
  "lastUpdated": "2023-06-25T14:27:00",
  "appUserId": 2,
  "restaurantId": 1,
  "public": true
}


### DELETE meal
DELETE {{url}}/8
Content-Type: application/json
